#!/bin/bash
#
# ./local_env
#
# local environment to adjust paths etc.
#
# (c) 2012, Ondics GmbH | githubler@ondics.de | www.ondics.de


# ip-address of l2p device (just for testing, later overridden by nagios-l2p.cfg)
ip_addr="10.0.0.108"

# directory for accessing the l2p scripts
dir_scripts="/usr/share/lufft-l2p-script-collection"


